spring:
  application:
    name: santader-dev-week
  datasource:
    url: jdbc:h2:mem:sdw
    username: sa
    password: admin
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true